### PR TITLE
Sets up Repo for the frontend

### PR DESCRIPTION
**Pull request by chidioguejiofor**
#### What does this PR achieve?
- installs dependencies for the app
- sets up react and react-router using Webpack
- sets up the folder structure of the app
- sets up the React Router for different parts of the app
- adds babel config to the app
- updates README

#### Any background context?
- We intend to use this project to learn the following patterns
   - styled components in JS
   - atomic design

#### Manual Testing Steps
- When you clone the repo
- Run `npm run dev`
- The LandingPage text should be displayed in your browser

#### Any new deployment instructions
- Nay

#### Relevant Trello Tickets
- [Setup Frontend Repo](https://trello.com/c/kbAZ4Siz/2-create-and-setup-frontend-repo)

### CODE REVIEW

**Comment by chidioguejiofor** [comment]
@ChineduOguejiofor I am expecting your review for this ASAP

**Comment by chineduknight** [comment]
This looks good,
How about the eslint configuration
Travis setup
I don't see anything on testing

**Comment by chineduknight** [comment]
Also, I think you add a rule that all commits should have at least one review before being merged
and a workflow ie pull from master create a branch merge back to master or staging as the case may be

**Comment by chineduknight** [comment]
branch naming convention just to add the name feature/[your-name]/[description] e.g ch-chinedu-login-ui

**Review by chineduknight — CHANGES_REQUESTED** [review]
looks good I added some comments

**Comment by chidioguejiofor** [comment]
@ChineduOguejiofor added some merge  rules to protect the `staging` branch
Screenshot 2019-11-27 at 2 50 43 PM

Also added Codeclimate to the app with some Codeclimate basic config. Once you approve we merge

**Pull request merged**
